import { useTranslations } from '../../i18n/utils';

const t = useTranslations();

/** Optimized image data generated by the page via astro:assets `getImage`. */
export interface OptimizedImage {
  src: string;
  srcSet?: string;
}

interface Props {
  image: OptimizedImage;
}

export default function Hero({ image }: Props) {
  // Registration is the one live action on the landing page.
  const ctaHref = '/registration';

  return (
    <section className="relative w-full overflow-hidden">
      <div className="relative h-screen w-full">
        {/* Background image (optimized AVIF, eager — this is the LCP element) */}
        <img
          src={image.src}
          srcSet={image.srcSet}
          sizes="100vw"
          alt="TU Dresden campus"
          className="absolute inset-0 h-full w-full object-cover object-center"
          loading="eager"
          fetchPriority="high"
        />

        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black/50" />

        {/* Content */}
        <div className="relative h-full flex flex-col items-center justify-center px-6 text-center pt-16">
          <div className="max-w-3xl mx-auto animate-fade-up">
            <h1
              className="font-display text-5xl md:text-6xl lg:text-7xl font-extrabold text-white leading-[1.1]"
              style={{ textShadow: '0 2px 12px rgba(0,0,0,0.5)' }}
            >
              {t('hero.title').split('|').map((line, i, arr) => (
                <span key={i}>
                  {line}
                  {i < arr.length - 1 && <br />}
                </span>
              ))}
            </h1>

            <p
              className="mt-5 text-white text-lg md:text-xl font-medium tracking-wide"
              style={{ textShadow: '0 1px 6px rgba(0,0,0,0.6)' }}
            >
              {t('hero.dates')}
            </p>

            <a
              href={ctaHref}
              className="mt-8 inline-flex items-center gap-2 px-8 py-3.5 rounded-md bg-tu-sky text-white font-semibold text-lg shadow-soft hover:bg-tu-blue active:scale-95 transition-all duration-200"
              style={{ animationDelay: '0.2s', animationFillMode: 'both' }}
            >
              {t('hero.cta')}
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
